language: java
jdk:
  - openjdk8
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.6"
  firefox: "49.0"
  sauce_connect:
    username: ${SAUCELABS_USERNAME}
    access_key: ${SAUCELABS_ACCESS_KEY}

cache:
  directories:
    - $HOME/.gradle/

# We depend on a WildFly deployment for some of the production
# .jar files. Download it and install just above our repo.
before_script:
  # - "export DISPLAY=:99"
  # - "export XVFB_DISPLAY=:99"
  # - "sh -e /etc/init.d/xvfb start"
  # - sleep 3 # give xvfb some time to start
  - wget http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz -O /tmp/wildfly-10.1.0.Final.tar.gz
  - pushd ..
  - tar -xvf /tmp/wildfly-10.1.0.Final.tar.gz
  - popd
  - ./scripts/travis-start-wildfly.sh

install: true

# The build step here also builds our Javadocs.
script:
  - cd psm-app
  - ./gradlew --no-daemon --console=plain clean cms-portal-services:build cms-web:apiDocs
  - ../scripts/travis-deploy-application.sh
  # - export FIREFOX_HOME="$HOME/firefox-49.0/firefox/firefox"
  - ./gradlew --debug --stacktrace test aggregate
  - cd ../

# Push the new Javadocs to our GitHub Pages site.
after_success:
  - ./scripts/push-javadoc-to-gh-pages.sh

# Build the Continuous Deployment private key
before_deploy:
  - ./scripts/travis-ssh-add.sh

# Continuous Deployment
deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy-ci.sh
  on:
    branch: master
